namespace AHI.Infrastructure.Audit.Constant
{
    public static class ImportErrorMessage
    {
        public const string IMPORT_ERROR_REQUIRED = "AUDIT.LOG.IMPORT_ERROR.REQUIRED";
        public const string IMPORT_ERROR_MAX_LENGTH = "AUDIT.LOG.IMPORT_ERROR.MAX_LENGTH";
        public const string IMPORT_ERROR_GENERAL_INVALID = "AUDIT.LOG.IMPORT_ERROR.GENERAL_INVALID";
        public const string IMPORT_ERROR_INVALID_VALUE_TYPE = "AUDIT.LOG.IMPORT_ERROR.INVALID_VALUE_TYPE";
        public const string IMPORT_ERROR_GENERAL_OUT_OF_RANGE = "AUDIT.LOG.IMPORT_ERROR.GENERAL_OUT_OF_RANGE";
        public const string IMPORT_ERROR_INVALID_OPTION = "AUDIT.LOG.IMPORT_ERROR.INVALID_OPTION";
        public const string IMPORT_ERROR_OUT_OF_RANGE = "AUDIT.LOG.IMPORT_ERROR.OUT_OF_RANGE";
        public const string IMPORT_ERROR_EQUAL_COMPARISON = "AUDIT.LOG.IMPORT_ERROR.EQUAL_COMPARISON";
        public const string IMPORT_ERROR_LESS_THAN_MIN_VALUE = "AUDIT.LOG.IMPORT_ERROR.LESS_THAN_MIN_VALUE";
        public const string IMPORT_ERROR_STRICT_LESS_THAN_MIN_VALUE = "AUDIT.LOG.IMPORT_ERROR.STRICT_LESS_THAN_MIN_VALUE";
        public const string IMPORT_ERROR_GREATER_THAN_MAX_VALUE = "AUDIT.LOG.IMPORT_ERROR.GREATER_THAN_MAX_VALUE";
        public const string IMPORT_ERROR_STRICT_GREATER_THAN_MAX_VALUE = "AUDIT.LOG.IMPORT_ERROR.STRICT_GREATER_THAN_MAX_VALUE";
        public const string IMPORT_ERROR_NOT_EXIST = "AUDIT.LOG.IMPORT_ERROR.NOT_EXIST";
        public const string IMPORT_ERROR_NOT_EXIST_OR_ACTIVE = "AUDIT.LOG.IMPORT_ERROR.NOT_EXIST_OR_ACTIVE";
        public const string IMPORT_ERROR_CHILD_NOT_EXIST = "AUDIT.LOG.IMPORT_ERROR.CHILD_NOT_EXIST";
        public const string IMPORT_ERROR_MARKUP_DUPLICATED = "AUDIT.LOG.IMPORT_ERROR.MARKUP_DUPLICATED";
        public const string IMPORT_ERROR_MARKUP_USED = "AUDIT.LOG.IMPORT_ERROR.MARKUP_USED";
        public const string IMPORT_ERROR_ALREADY_HAVE_MARKUP = "AUDIT.LOG.IMPORT_ERROR.ALREADY_HAVE_MARKUP";
        public const string IMPORT_ERROR_METRIC_DUPLICATED = "AUDIT.LOG.IMPORT_ERROR.METRIC_DUPLICATED";
        public const string IMPORT_ERROR_METRIC_INCONSISTENT = "AUDIT.LOG.IMPORT_ERROR.METRIC_INCONSISTENT";
        public const string IMPORT_ERROR_GENERAL_ALARM_RULE_LIMIT = "AUDIT.LOG.IMPORT_ERROR.GENERAL_ALARM_RULE_LIMIT";
        public const string IMPORT_ERROR_ANALOG_ALARM_RULE_LIMIT = "AUDIT.LOG.IMPORT_ERROR.ANALOG_ALARM_RULE_LIMIT";
        public const string IMPORT_ERROR_PER_SIGNAL_ALARM_RULE_LIMIT = "AUDIT.LOG.IMPORT_ERROR.PER_SIGNAL_ALARM_RULE_LIMIT";
        public const string IMPORT_ERROR_ALARM_RULE_THRESHOLD_ORDER = "AUDIT.LOG.IMPORT_ERROR.ALARM_RULE_THRESHOLD_ORDER";
        public const string IMPORT_ERROR_GET_FILE_FAILED = "AUDIT.LOG.IMPORT_ERROR.GET_FILE_FAILED";
        public const string IMPORT_ERROR_PAYLOAD_INVALID = "AUDIT.LOG.IMPORT_ERROR.PAYLOAD_INVALID";
        public const string IMPORT_ERROR_KEYTYPE_ONLY_ONCE = "AUDIT.LOG.IMPORT_ERROR.KEYTYPE_ONLY_ONCE";
        public const string IMPORT_ERROR_TEMPLATE_BINDING_TYPE_INVALID = "AUDIT.LOG.IMPORT_ERROR.TEMPLATE_BINDING_TYPE_INVALID";
        public const string IMPORT_ERROR_TEMPLATE_DETAIL_TYPE_INVALID = "AUDIT.LOG.IMPORT_ERROR.TEMPLATE_DETAIL_TYPE_INVALID";
        public const string IMPORT_ERROR_TEMPLATE_DETAIL_METRIC_TYPE_INVALID = "AUDIT.LOG.IMPORT_ERROR.TEMPLATE_DETAIL_METRIC_TYPE_INVALID";
        public const string INGESTION_ERROR_INVALID_CSV_FORMAT = "AUDIT.LOG.INGESTION_ERROR.INVALID_CSV_FORMAT";
        public const string IMPORT_ERROR_INVALID_TABLE_SCHEMA = "AUDIT.LOG.INVALID_TABLE_SCHEMA";
    }
}